### ISSUE TITLE
makeObservable crashing on class derived from ObservableMap for mobx 6.1.x

### ISSUE THREAD

**Issue by thunderkid** [mobxjs/mobx#2765]
**Intended outcome:**
Should be able to derive class from `ObservableMap` and run `makeObservable(this)` in its constructor.
This code works in `mobx@6.0.5` but breaks in `mobx@6.1.x`:

```
export class ObservableMapLimitedSize<T> extends ObservableMap<string, T> {
    earliestVisible: number = 0;
    latestVisible: number = 0;

    constructor(private maxLength: number) { 
        super(); 
        makeObservable(this);
    }
    ...
```

**Actual outcome:**
In `mobx@6.1.x` it throws the error `adm.make_ is not a function` at `makeObservable.ts:38`

**How to reproduce the issue:**
Run the code above.

**Versions**
Getting the crash in `mobx@6.1.x`. It worked fine in `mobx@6.0.x`.

**Comment by mweststrate** [comment]
Extending builtins is not something we support. I recommend to delegate it
with a getter/setter to a separate object stored on the instance.

**Comment by urugator** [comment]
@mweststrate Should we add
`if (__DEV__ && this.constructor !== BuiltinType) die("Extending is not supported")`
to builtin constructors?

**Comment by thunderkid** [comment]
Yes, delegating fixes it pretty easily but I didn't realize there was a restriction on extending builtins.

I'm trying to understand why builtins should have more restrictions than my own classes. `ObservableMap` is just defined in the `mobx` library by some typescript code, so if I'd used this same typescript code in my own files, that presumably would have failed too. So what aspect of the implementation makes it fail? Is it because of the `observe_` and `intercept_` properties, or is there something else more general that causes it to fail?

**Comment by iChenLei** [comment]
### After `annotations + subclassing rework`  #2641 

![2021-01-31 13 28 43](https://user-images.githubusercontent.com/14012511/106375681-1f525d80-63c9-11eb-94cf-ee6d94105700.png)
When you extending builtins, the `asObservableObject` return a plain object `{}`
Call `adm.make_` will crash cause `adm.make_ is not a function`

### Why ?
![2021-01-31 13 33 04](https://user-images.githubusercontent.com/14012511/106375692-3c872c00-63c9-11eb-87ba-1c08eae0693c.png)
![2021-01-31 13 33 38](https://user-images.githubusercontent.com/14012511/106375696-44df6700-63c9-11eb-84c6-ff6271df18bd.png)
 
Cause `ObservableMap`and `ObservableSet` has default `[$mobx]` property.
> https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/types/observableobject.ts#L650-L667
```js
   // when the superclass don't have `[$mobx]` property,
   // we will create a new ObservableObjectAdministration(a.k.a adm
    const adm = new ObservableObjectAdministration(
        target,
        new Map(),
        stringifyKey(name),
        getAnnotationFromOptions(options),
        options?.autoBind
    )
   //  so `adm.make_` won't crash. 🎉 
    addHiddenProp(target, $mobx, adm)
```
So that's why we encount this issue.  @thunderkid 

### Summary
I don't know is it bug or feature, I create a pr for warn this action.

**Comment by thunderkid** [comment]
@iChenLei 
Thanks for the explanation!

**Comment by mispy** [comment]
I'm also getting a crash in makeObservable 6.1.x during SSR with a different error `defaultAnnotation must be valid annotation` (I downgraded to 6.0.5 for now)

**Comment by iChenLei** [comment]
#### The error msg from here
> https://github.com/mobxjs/mobx/blob/main/packages/mobx/src/types/observableobject.ts#L113
```ts
        if (__DEV__ && !isAnnotation(this.defaultAnnotation_)) {
            die(`defaultAnnotation must be valid annotation`)
        }
```
We need minimal reproduction code(codesandbox, github repo, etc.) to debug, so please provide more info about your problem, Thank you. A new `issue` is better. @mispy

**Comment by urugator** [comment]
@thunderkid Extending itself is not such of a problem, but we still don't support it, because you can mess things up in various ways and we don't want to take reponsibility for that.
The problem is trying to turn one kind of observable (map) into other kind of observable (object) - their internal implementation is different and incompatible with one another.
Observable object and observable map are treated as 2 different things/types atm, meaning you can't have a map that is also an object...
