### ISSUE TITLE
Unit test fails in angular 8 with 5.15 version

### ISSUE THREAD

**Issue by anandshanbhag** [mobxjs/mobx#2193]
The unit test seems to be failing while running in the headless chrome mode in Angular

version details are below;
mobx : 5.15.0
angular: 8.1.0
`
ERROR in ../node_modules/mobx/lib/api/flow.d.ts:8:83 - error TS2315: Type 'Generator' is not generic.
8 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;~~~~~~~~~~~~~~~~~~~~~~
../node_modules/mobx/lib/api/flow.d.ts:8:108 - error TS2304: Cannot find name 'AsyncGenerator'.
8 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
`

Note: Everything works perfectly with version 5.14.2

**Comment by tiagoaguiar100** [comment]
Hi @anandshanbhag , the latest version of mobx requires typescript > 3.6.0 but the latest of @angular/compiler-cli requires typescript >=3.4.0 and <3.6.0.

In the end, I think it's better to stick with mobx 5.14.2

**Comment by johnhamm** [comment]
This effectively makes mobx versions higher than 5.14.2 incompatible with Angular.

**Comment by FredyC** [comment]
@johnhamm Did someone open an issue with Angular then? Obviously this is something that should be solved on their side.
