### ISSUE TITLE
Cannot call method in child component

### ISSUE THREAD

**Issue by odesey** [mobxjs/mobx#2273]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:
2. [ X] Issue:

I am using mobx in a react-native project with a Parent to children setup like below:

```javascript

@inject('myStore')
@observer
class Parent extends Component {
  constructor(props) {
    super(props);
    this.child = React.createRef();
  }

  onPress = () => {
    this.child.current.getAlert();
  };

  render() {
    return (
      <View>
          <Child ref={this.child} />
          <Sibling onPress={this.onPress} />
      </View>
    );
  }
}

@inject('myStore')
@observer
class Child extends Component {
  getAlert = () => {
    console.log('called from parent');
  }

  render() {
    return <Text>Hello</Text>;
  }
}

@inject('myStore')
@observer
class Sibling extends Component {

  render() {
    return <button onPress={this.props.onPress}>Press Me</button>;
  }
}
```

When I attempt to call the method in the `<Child />` component from the `<Sibling />` or `<Parent />` I get an error that says:

**_this.child.current.getAlert() is not a function**
**_this.child.current.getAlert() is undefined**

If I remove the `@inject('myStore')`  and `@observer` from the `<Child />` component, the method call works as expected.

I have a few questions:

1 - Is this a bug?
2 - How can I call the method in the child component from the sibling component?
3 - Can I use mobx to make method calls?

Thanks.

Forgot to include versions:

   **mobx:**  4.15.4
   **mobx-react:** 5.4.4
   **react-native:** 0.61.2

**Comment by FredyC** [comment]
First and foremost, would you perhaps reconsider that pattern? Direct communication between components is a kinda bad practice. I am not sure what you are trying to achieve in a specific case.

Either way, please provide a reproduction with eg. CodeSandbox so we can have a closer look at what's happening there.

**Comment by mweststrate** [comment]
The ref will point at the HoC. I think you can access the wrapped component
by using .wrappedInstance IIRC, but anyway this is a bit of an anti pattern
in React except for basically DOM based components. props are the public
api of your component, so pass callbacks or the state that should propagate
through props instead. Also note that you can't use this pattern anymore
with functional / hooks component.

**Comment by odesey** [comment]
Thanks for your response @FredyC and @mweststrate  , I am still considering a re-factor but havent been able to come up with one. Let me explain in greater detail why this design came about.

Keep in mind this is a `react-native` app. I have a screen that mimics the Google maps screen shown below:

This screen has 4 main components:
`<SearchScreen />` -- This is the parent screen where all the data requests takes place and is passed to the children. It is also a Class based component

`<Maps />` -- This is the `react-native-maps` component that receives data from the `<SearchScreen />`, Maps is also class based.

`<SearchBar />` -- Component to the top of the screen with the search box and `Search this area` button. This is also classed based

Lastly we have `<SearchResults />` -- This is a class based component that has the Carousel and 2 FAB buttons (location and results list). This component is special because of the reveal and hide animation that uses `react-native-reanimated`

The `SearchResults` component has child components ( 2 FAB buttons and Carousel) that must be rendered in the same component for the animation shown in the GIF to work.

When I press the location button (in the `SearchResults` component, I need to call a method in the `Maps` component that animates to the user's location. In addition, when I move the carousel, I need to make another call from the `Carousel` component to the `Maps` component to center the marker that matches the current carousel card. 

I am not a developer by trade and am completely open to suggestions about doing this better!

This was a lot to take in hopefully i can sum it up nicely:

SearchScreen <-- SearchBar (Initiates search function in SearchScreen, child of SearchScreen to contain its own state and prevent unnecessary re-renders of SearchScreen)

SearchScreen --> Maps (Search results sent to maps as an array for maps to render markers)

SearchScreen --> SearchResults (search results sent as array (to initiate animation)  and to child (Carousel ))

SearchResults (2 children `FAB Buttons` and `Carousel`) <--> Maps

Maps <--> Carousel (when map marker is selected, carousel updates, when carousel is swiped, maps re-centers on carousel item)

Fab Button --> Maps (when user presses location button, map moves to user location)

***

Screenshot (from Google Maps)
Gif (from app I am working on)

![Screenshot_20200207-085029](https://user-images.githubusercontent.com/3899366/74037055-7c206100-498b-11ea-83fb-07611b4c9386.jpg)


![ezgif-7-50839d560f30](https://user-images.githubusercontent.com/3899366/74041133-17690480-4993-11ea-805f-9d99cfa2a67a.gif)


Hopefully this clears up why I need to call sibling methods :-)

Thanks.

**Comment by mweststrate** [comment]
The way I would go about that, is in the parent create and pass down an object that can coordinate those things. That could even be a simple event emitter, e.g. pass an object down on which one component can trigger (e.g. `fireCenterUser()` and the other one can listen and interpret those thinngs, e.g. by implementing an `onCenterUser(callback)`. 

Since you are using MobX, you could also use observables in this object, and setup a reaction, like `reaction(() => { x: viewState.userX, : viewState.userY }, () => startAnimation)`, where `viewState` is the observable object passed down from the parent to both components. This way you keep the components technically independent, and can change the layout structure or test them independently without breaking things.

**Comment by odesey** [comment]
Thanks for the quick response @mweststrate , based on your answer I think I have one of the 2 problems solved conceptually.

I am assuming that when you say `listen and interpret` you mean using the 'componentDidUpdate()` function in the child components?

For the `<Carousel />` to `<Maps />` relationship, I can use `MobX` to store an observable value (like carousel index). When I swipe I can update the value in my store and then in the `<Maps />` component, I can use the `componentDidUpdate () {...do stuff}` to center the map? Is this what you are referring to? 

I still do not get how to use `MobX` to center the map when the user taps the location button however, as nothing is "changing" that I am keeping track of in `MobX`. Even if the users moves away from their current location I do not track it, I simply want when the users presses the button I call a method on the `Maps` component to go to their current location. Hhow can I do that using `MobX`? Do I need to track is they move away so that `MobX` can fire an event (like latitude and longitude have changed, make some `@observable or `@autorun` or `@reaction` value true?

Thanks again for your help, greatly appreciated!

**Comment by odesey** [comment]
Solved this problem by utilizing this package:

https://github.com/meinto/react-native-event-listeners#readme

Thanks for the help.
